name: Copy HTML to Deployment

on:
  push:
    branches:
      - main  # Modify this according to your branch

jobs:
  copy-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v2

    - name: Copy folder to destination repository
      run: |
        mkdir -p destination-folder
        cp -r /html/build/dist/* destination-folder/

    - name: Checkout destination repository
      uses: actions/checkout@v2
      with:
        repository: LUL-Game-Development-Group-6/deployment
        path: destination-folder
        ref: main  # Modify this according to your branch

    - name: Commit and push changes to destination repository
      run: |
        cd destination-folder
        git add .
        git config --global user.email "github-actions@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git commit -m "DEPLOYMENT COMMIT"
        git push origin main  # Modify this according to your branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
